import { Outfit } from 'next/font/google';
import './globals.css';
import { AppContextProvider } from '@/context/AppContext';
import { Toaster } from 'react-hot-toast';
import { ClerkProvider } from '@clerk/nextjs';
import { jaJP } from '@clerk/localizations';

const outfit = Outfit({ subsets: ['latin'], weight: ['300', '400', '500'] });

const customJaLocalization = {
  ...jaJP,
  formFieldLabel__username: 'ユーザー名(アルファベットと数字のみ)',
  signUp: {
    ...jaJP.signUp,
    username: 'ユーザー名(アルファベットと数字のみ)',
    usernamePlaceholder: '英字のみ入力してください',
    formButtonPrimary: 'サインアップ',
    formFieldLabel__username: 'ユーザー名（英字のみ）',
    continue: {
      ...jaJP.signUp.continue,
      username: 'ユーザー名(アルファベットと数字のみ)',
    },
  },
};

export const metadata = {
  title: 'Kabe Gallery',
  description: 'E-Commerce with Next.js ',
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider localization={customJaLocalization}>
      <html lang="en">
        <body className={`${outfit.className} antialiased text-gray-700`}>
          <Toaster />
          <AppContextProvider>{children}</AppContextProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}

// import {
//   ClerkProvider,
//   SignInButton,
//   SignUpButton,
//   SignedIn,
//   SignedOut,
//   UserButton,
// } from "@clerk/nextjs";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Clerk Next.js Quickstart",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <ClerkProvider>
//       <html lang="en">
//         <body
//           className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//         >
//           <header className="flex justify-end items-center p-4 gap-4 h-16">
//             <SignedOut>
//               <SignInButton />
//               <SignUpButton />
//             </SignedOut>
//             <SignedIn>
//               <UserButton />
//             </SignedIn>
//           </header>
//           {children}
//         </body>
//       </html>
//     </ClerkProvider>
//   );
// }
